version: '3.9'
services:
 mongo-db:
  container_name: "healthcare-api-database"
  image: mongo:latest
  volumes:
   - mongo-db-vol:/data/db
 node-api:
  container_name: "node-api"
  build: .
  ports:
   - 4000:7000
  environment:
   MONGO_URI: mongodb://healthcare-api-database:27017
  volumes:
   - .:/usr/src/app
   - /usr/src/app/node_modules
  depends_on:
   - mongo-db

volumes:
 mongo-db-vol: